version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=luis
      - MONGO_INITDB_ROOT_PASSWORD=alvarez
    volumes:
      - /mongo_data:/data/db
